### ISSUE TITLE
Azure Function to receive event grid actions on deadletters

### ISSUE THREAD

**Issue by Alex-Potter-Dixon** [glasswall-sre/dead-letter-watcher#1]
A main azure function to receive the dead letter and depending on the service map to other functions to handle further functionality. I.E If stuck in STMPTransmission then reconstruct the email option.

**Comment by tpilvelis-gw** [comment]
I'm shooting in the dark here with Azure, 
Azure Event Grid Trigger,
Azure Service Bus Queue Trigger
Azure Service Bus Topic Trigger 
seem to be options
