### ISSUE TITLE
[bug] SonarCloud Bug - Correct one of the identical sub-expressions on both sides of operator "=="

### ISSUE THREAD

**Issue by AshKapow** [glasswall-sre/dead-letter-watcher#30]
deadletter_listener/tests/deadletter_watcher/test_datadog.py

L79

`assert 1 == 1`

https://sonarcloud.io/project/issues?id=dead-letter-watcher&issues=AXUJFCMS9L7EMUjjI5yP&open=AXUJFCMS9L7EMUjjI5yP

**Comment by njogumbau** [comment]
Fix - https://github.com/glasswall-sre/dead-letter-watcher/pull/31

**Comment by mukulgupta2138** [comment]
Verified, this is now fixed.
