### ISSUE TITLE
Enhance the Architectural Diagram - Using PlantUml

### ISSUE THREAD

**Issue by chrisdiao** [glasswall-sre/dead-letter-watcher#43]
Enhance the architectural diagram using PlantUml - C4 Model
Lets start with the "Context - Level 1" 
![image.png](https://images.zenhubusercontent.com/5f43cee726e80382e54a0b0f/8e97fdfb-a730-4123-ae40-6b4f074bb94d)

**Comment by mukulgupta2138** [comment]
Created a PR around this https://github.com/glasswall-sre/dead-letter-watcher/pull/46
